AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ai-bot-bedrock

  Sample SAM Template for ai-bot-bedrock

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Parameters:
  ProjectName:
    Type: String
    Default: ai-bedrock
    Description: (Required) The name of the project
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_-]+$
    ConstraintDescription: "Required. Can be characters, hyphen, and underscore only. No numbers or special characters allowed."
  StageName:
    Type: String
    Default: dev
    Description: (Required) Enter dev, prod. Default is dev.
    AllowedValues:
      - dev
      - prod
  DatabaseUri:
    Type: String
    Description: DB connection string
  KnowledgeBaseId:
    Type: String
    Description: Bedrock Knowledge Base Id
  DatasourceId:
    Type: String
    Description: Bedrock Datasource Id

Resources:
  CallBedrockSQLFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/call-bedrock-sql/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          DatabaseUri: !Ref DatabaseUri
      Timeout: 120
      Architectures:
        - x86_64
      Events:
        CallBedrock:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /call-bedrock-sql
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action: "bedrock:*"
              Resource: "*"
  CallBedrockKBFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/call-bedrock-kb/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          KnowledgeBaseId: !Ref KnowledgeBaseId
          DatasourceId: !Ref DatasourceId
      Architectures:
        - x86_64
      Events:
        CallBedrock:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /call-bedrock-kb
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action: "bedrock:*"
              Resource: "*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AIBotAPI:
    Description: API Gateway endpoint URL for Prod stage for Call Bedrock function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CallBedrockFunction:
    Description: Call Bedrock Lambda Function ARN
    Value: !GetAtt CallBedrockFunction.Arn
  CallBedrockFunctionIamRole:
    Description: Implicit IAM Role created for Call Bedrock function
    Value: !GetAtt CallBedrockFunctionRole.Arn
